### ISSUE TITLE
Drone Geo Referencer Service doesn't always get the results on the first time of the request

### ISSUE THREAD

**Issue by dafnaweiss** [Webiks/ansyn#32]
Bug related to **issue #12** :
Drone Geo Referencer Service, doesn't always get the results on the first time of the request but only on the 2cd time of the same rerquest
**examples:**
**directory: Karkur 14-12-18**
- DJI_0305 - got results on 1st try (1 minute)
- DJI_0307 - got results on 1st try (35 seconds)
- DJI_0308 - got results on 1st try (30 seconds)
- DJI_0309 - got results on 1st try (30 seconds)
- DJI_0320 - got results on 1st try (10 seconds)
- DJI_0317 - got results on 1st try
- DJI_0318 - got results on 1st try
- DJI_0310 - got results on 2cd try (1 minute). FAILED on 1st try (30 seconds)
- DJI_0315 - got results on 2cd try (40 seconds). FAILED on 1st try (40 seconds)
- DJI_0319 - got results on 2cd try (15 seconds). FAILED on 1st try (45 seconds)
- DJI_0323 - got results on 2cd try. FAILED on 1st try

**Comment by dafnaweiss** [comment]
the bug was fixed by adding timeout to the setView function.
this is working for now. in the future we'll try to found another solution

**Comment by idanbarak** [comment]
Two sub tasks

- [ ] failure on first request

- [ ] Response time
